# Test config for ArrakisND
arrakis_nd:
  verbose:   true
  flow_folder:  '/local_data/'
  flow_files:   'hdf5'
  skip_files: []
  plugin_locations: []

plugins:
  DaughterPlugin:
  TrackIDHitMapPlugin:
  TrackPlugin:
  ParticlePlugin: