# Test config for ArrakisND
arrakis_nd:
  process_type:      "npz"  # npz or flow
  simulation_folder: "/local_data/"
  simulation_files:  "all"
  skip_files:   []
  skip_event:   0
  skip_events:  [0, 1000, 2000]
  output_folder:  "/local_data/"
  verbose:  true
  gpu:      false
  gpu_device: 0
  debug:  true
  multi_processing: false
  # wrangler parameters
  shower_threshold: 20
  ionization_influence_distance:  4
