# Test config for ArrakisND
arrakis_nd:
  process_type:      "npz"  # npz or flow
  simulation_folder: "/local_data/"
  simulation_files: [
    "MiniRun4_1E19_RHC.flow.00000.FLOW.h5"
  ]
  verbose:  true
  gpu:      true
  gpu_device: 0
  debug:  true
  shower_threshold: 20
