# Test config for ArrakisND
arrakis_nd:
  process_type:      "npz"  # npz or flow
  simulation_folder: "/global/cfs/cdirs/dune/www/data/2x2/simulation/productions/MiniRun4_1E19_RHC/MiniRun4_1E19_RHC.flow/FLOW/"
  simulation_files: [
    "MiniRun4_1E19_RHC.flow.00000.FLOW.h5",
    "MiniRun4_1E19_RHC.flow.00001.FLOW.h5",
    "MiniRun4_1E19_RHC.flow.00002.FLOW.h5",
    "MiniRun4_1E19_RHC.flow.00003.FLOW.h5",
    "MiniRun4_1E19_RHC.flow.00004.FLOW.h5",
    "MiniRun4_1E19_RHC.flow.00005.FLOW.h5",
    "MiniRun4_1E19_RHC.flow.00006.FLOW.h5",
    "MiniRun4_1E19_RHC.flow.00007.FLOW.h5",
    "MiniRun4_1E19_RHC.flow.00008.FLOW.h5",
    "MiniRun4_1E19_RHC.flow.00009.FLOW.h5",
    "MiniRun4_1E19_RHC.flow.00010.FLOW.h5",
    "MiniRun4_1E19_RHC.flow.00011.FLOW.h5",
    "MiniRun4_1E19_RHC.flow.00012.FLOW.h5",
    "MiniRun4_1E19_RHC.flow.00013.FLOW.h5",
    "MiniRun4_1E19_RHC.flow.00014.FLOW.h5"
  ]
  skip_files:   []
  skip_events:  [
    0, 1000, 2000, 3000, 4000,
    5000, 6000, 7000, 8000,
    9000, 10000, 11000, 12000,
    13000, 14000
  ]
  output_folder:  "/local_data/"
  verbose:  true
  gpu:      true
  gpu_device: 0
  debug:  true
  # wrangler parameters
  shower_threshold: 20
  ionization_influence_distance:  4
