# Test config for ArrakisND
arrakis_nd:
  verbose:   true
  flow_folder:  '/global/cfs/cdirs/dune/www/data/2x2/simulation/productions/MiniRun5_1E19_RHC/MiniRun5_1E19_RHC.flow.beta2a/FLOW/0000000'
  flow_files:   'hdf5'
  skip_files: ['Backup_MiniRun5_1E19_RHC.flow.0000000.FLOW.hdf5']
  arrakis_folder: '/global/cfs/cdirs/dune/www/data/2x2/people/ncarrara/'
  plugin_locations: []
  hit_type: 'prompt'

plugins:
  DaughterPlugin:
  TrackIDHitMapPlugin:
  ParentPlugin:
  AncestorPlugin:
  SegmentPlugin:
  TrackPlugin:
    deuteron_track_threshold: 10
  DeltaPlugin:
    delta_size_threshold: 100
  MichelPlugin:
  FragmentPlugin:
    compton_blip_threshold: 50
    conversion_blip_threshold: 50
    other_blip_threshold: 50
  PhotonPlugin:
  IonPlugin:
    deuteron_track_threshold: 10
  NeutronPlugin:
  NeutrinoPlugin:
  ShowerPlugin:
  ParticlePlugin:
  ConstraintPlugin:
    segment_influence_cut: 5
    constraint_mode: "min_distance"
    replace_undefined: 2
  # HeatMapPlugin:
  #   vertex_variance: 1.0
  #   tracklette_begin_variance: 1.0
  #   tracklette_end_variance: 1.0
  #   fragment_begin_variance: 1.0
  #   fragment_end_variance: 1.0
  #   shower_begin_variance: 1.0