# Test config for ArrakisND
arrakis_nd:
  verbose:   true
  flow_folder:  '/global/cfs/cdirs/dune/www/data/2x2/simulation/productions/MiniRun5_1E19_RHC/MiniRun5_1E19_RHC.flow.beta1/FLOW/0000000'
  flow_files:   'hdf5'
  skip_files: []
  arrakis_folder: '/local_scratch/MiniRun5_1E19_RHC/MiniRun5_1E19_RHC.flow/FLOW'
  plugin_locations: []

plugins:
  DaughterPlugin:
  TrackIDHitMapPlugin:
  TrackPlugin:
  ParticlePlugin: